### ISSUE TITLE
півкласу пішло

### ISSUE THREAD

**Issue by msklvsk** [mova-institute/zoloto#274]
<img width="274" alt="image" src="https://user-images.githubusercontent.com/473012/42424812-61368e6a-831b-11e8-8e85-dc0229555f56.png">

Або візьмімо _півкласу читає_  / _півкласу пішло_ для орфографічної нормативності. Як натягнути це на нашу теорію? 

Можна вважати, що це [multiword token](http://universaldependencies.org/u/overview/tokenization.html) і в синті розбивати на _половина класу читає_, але мулятиме неузгодження _половина класу пішло_. Або можна сказати, що це такий хитрий невідмінюваний іменник. Але уявіть його в орудному і місцевому. І якого _півкласу_ роду? І чи ви в голові його сприймаєте як один іменник?

Пропоную розбивати, а неузгодження вважати аналогічним _три людини пішло_.
(Саме збираюсь додати multiword token’и для ні́ким, ні́де, решти.)

**+**
Ще зауважте, що є півострів, [_піваркуш_](http://sum.in.ua/s/pivarkush) — з повноцінною парадигмою і родом, і навіть _півхата_ в Тютюнника була.

**++**
Зі школи не розумію цю орфографію. Чому не _пів класу_, де _пів_, як _півтора_, — числівник.

**+++**
Дійсно, можна розбивати не на _половина класу_, а на _пів класу_, і додати _пів_-числівник.

**++++**
В Харківському окремо! <img width="828" alt="image" src="https://user-images.githubusercontent.com/473012/42425350-bef79338-8324-11e8-95bc-4af8258da8f1.png">

**Comment by msklvsk** [comment]
Джерело — Харківський правопис. І правопис-99 теж.
[Правопис-1928.pdf](https://github.com/mova-institute/zoloto/files/2175508/-1928.pdf) сторінка 39

**Comment by natko5** [comment]
Ясно, польською все це теж окремо пишеться.
Так чи інакше, ми мусимо чинним правописом керуватися, а цим  хіба що інспіруватися ))
Ще один приклад на узгодження:
"... далі, півкласу нормальних з ним так же нормально спілкуються, а інші півкласу такі озабочені особистості, яким просто всеодно."
В українській є сильна варіативність узгодження між підметом і присудком, так само всередині числівникових фраз в ролі підмета і вони ж плюс присудок. Тобто тут нічого принципово нового немає. Лишається узгодити технічні деталі.
