### ISSUE TITLE
ні́ з ким

### ISSUE THREAD

**Issue by msklvsk** [mova-institute/zoloto#276]
Продовжуючи #275:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/473012/42543947-03322c8c-84b7-11e8-9c4e-d89a80e8c7c2.png">

Дати _ні_ морфо від _немає_?: `verb:imperf:pres:s:3:neg`, щоб паралельно до [ageieva__ya_obizvusia_do_nykh/22?focus=T5](https://lab.mova.institute/brat/#/ud/ageieva__ya_obizvusia_do_nykh/22?focus=T5)

**Comment by natko5** [comment]
Морфо так. То виходить _ буде_ ` aux`, воно спокійно опускається.
